# Generated by Django 5.2.7 on 2025-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=50)),
                ('url_text', models.CharField(max_length=2048)),
                ('data_accesare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
