# Generated by Django 5.2.7 on 2025-12-20 16:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=50)),
                ('url_text', models.CharField(max_length=2048)),
                ('data_accesare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_ingredient', models.CharField(max_length=100, unique=True)),
                ('este_alergen', models.BooleanField(default=False)),
                ('detalii_alergen', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Optiuni_blat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_blat', models.CharField(max_length=100, unique=True)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('calorii', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opțiuni Blaturi',
            },
        ),
        migrations.CreateModel(
            name='Optiuni_crema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_crema', models.CharField(max_length=100, unique=True)),
                ('insertie_fructe', models.BooleanField(default=False)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('calorii', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opțiuni Creme',
            },
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_prajitura', models.CharField(max_length=255)),
                ('descriere_prajitura', models.TextField(blank=True, null=True)),
                ('gramaj', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(choices=[('RV', 'Red Velvet'), ('CS', 'Cheesecake'), ('CR', 'Cinnamon Rolls'), ('TR', 'Tarta'), ('EC', 'Ecler'), ('AL', 'Altul')], default='AL', max_length=2)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='media/prajituri')),
                ('ingrediente', models.ManyToManyField(to='Cofetarie.ingrediente')),
            ],
            options={
                'verbose_name_plural': 'Prajituri',
            },
        ),
        migrations.CreateModel(
            name='Tort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_personalizat', models.CharField(max_length=255)),
                ('pret_calculat', models.DecimalField(decimal_places=2, default=0.0, help_text='Pretul va fi calculat automat la salvare', max_digits=8)),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('descriere_tort', models.TextField(blank=True, null=True)),
                ('gramaj', models.IntegerField()),
                ('calorii', models.IntegerField(default=0, help_text='Numarul de calorii va fi calculat automat la salvare')),
                ('blat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torturi_cu_acest_blat', to='Cofetarie.optiuni_blat')),
                ('crema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torturi_cu_aceasta_crema', to='Cofetarie.optiuni_crema')),
                ('ingrediente', models.ManyToManyField(blank=True, related_name='ingrediente_in_torturi', to='Cofetarie.ingrediente')),
            ],
            options={
                'verbose_name': 'Tort',
                'verbose_name_plural': 'Torturi',
            },
        ),
        migrations.CreateModel(
            name='Optiuni_decoratiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_decoratiune', models.CharField(max_length=100, unique=True)),
                ('detalii', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoratiuniunile_tortului', to='Cofetarie.tort')),
            ],
            options={
                'verbose_name': 'Opțiune Decorațiune',
                'verbose_name_plural': 'Opțiuni Decorațiuni',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(help_text='Format: 07xxxxxxxx', max_length=10)),
                ('adresa', models.CharField(max_length=100, verbose_name='Adresă Completă')),
                ('oras', models.CharField(max_length=50, verbose_name='Oraș')),
                ('data_nasterii', models.DateField(blank=True, help_text='Format: AAAA-LL-ZZ', null=True)),
                ('promotii', models.BooleanField(default=False, verbose_name='Vreau să primesc oferte pe email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
