# Generated by Django 5.2.7 on 2025-12-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cofetarie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
