# Generated by Django 5.2.7 on 2025-10-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cofetarie', '0002_locatie_organizator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_ingredient', models.CharField(max_length=100, unique=True)),
                ('este_alergen', models.BooleanField(default=False)),
                ('detalii_alergen', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Optiuni_blat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_blat', models.CharField(max_length=100, unique=True)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('calorii', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opțiuni Blaturi',
            },
        ),
        migrations.CreateModel(
            name='Optiuni_crema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_crema', models.CharField(max_length=100, unique=True)),
                ('insertie_fructe', models.BooleanField(default=False)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('calorii', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Opțiuni Creme',
            },
        ),
        migrations.CreateModel(
            name='Tort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_personalizat', models.CharField(max_length=255)),
                ('pret_calculat', models.DecimalField(decimal_places=2, default=0.0, help_text='Pretul va fi calculat automat la salvare', max_digits=8)),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('descriere_tort', models.TextField(blank=True, null=True)),
                ('gramaj', models.IntegerField()),
                ('calorii', models.IntegerField(default=0, help_text='Numarul de calorii va fi calculat automat la salvare')),
                ('blat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torturi_cu_acest_blat', to='Cofetarie.optiuni_blat')),
                ('crema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='torturi_cu_aceasta_crema', to='Cofetarie.optiuni_crema')),
                ('ingrediente', models.ManyToManyField(blank=True, related_name='ingrediente_in_torturi', to='Cofetarie.ingrediente')),
            ],
            options={
                'verbose_name': 'Tort',
                'verbose_name_plural': 'Torturi',
            },
        ),
        migrations.CreateModel(
            name='Optinuni_decoratiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_decoratiune', models.CharField(max_length=100, unique=True)),
                ('detalii', models.TextField(blank=True, null=True)),
                ('pret', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoratiuniunile_tortului', to='Cofetarie.tort')),
            ],
            options={
                'verbose_name': 'Opțiune Decorațiune',
                'verbose_name_plural': 'Opțiuni Decorațiuni',
            },
        ),
    ]
