# Generated by Django 5.2.7 on 2026-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cofetarie', '0003_promotie_vizualizare'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogareSuspecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('data_incercare', models.DateTimeField(auto_now_add=True)),
                ('username_incercat', models.CharField(max_length=100)),
            ],
        ),
    ]
