# Generated by Django 5.2.7 on 2025-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cofetarie', '0003_ingrediente_optiuni_blat_optiuni_crema_tort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prajitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_prajitura', models.CharField(max_length=255)),
                ('descriere_prajitura', models.TextField(blank=True, null=True)),
                ('gramaj', models.IntegerField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(choices=[('RV', 'Red Velvet'), ('CS', 'Cheesecake'), ('CR', 'Cinnamon Rolls'), ('NG', 'Negresa'), ('EC', 'Ecler'), ('AL', 'Altul')], default='AL', max_length=2)),
                ('ingrediente', models.ManyToManyField(to='Cofetarie.ingrediente')),
            ],
        ),
    ]
