# Generated by Django 5.2.7 on 2025-11-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cofetarie', '0004_prajitura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prajitura',
            options={'verbose_name_plural': 'Prajituri'},
        ),
        migrations.AddField(
            model_name='prajitura',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='media/prajituri'),
        ),
    ]
